name: Add new issues to GitHub Project v2

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      project: write
    steps:
      - name: Add issue to GitHub Project
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/Mathiszeggane/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}


