name: Add issue to GitHub Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to GitHub Project
        uses: peter-evans/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/Mathiszeggane/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
